# Generated by Django 2.2.4 on 2019-08-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=250, null=True)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
