# Generated by Django 2.2.4 on 2019-08-23 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('return_count', models.IntegerField()),
                ('user', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='requestId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Access'),
        ),
    ]
