# Generated by Django 2.2.4 on 2019-08-23 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190823_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='requestId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Access'),
        ),
    ]
