# Generated by Django 2.2.4 on 2019-08-23 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190823_1616'),
    ]

    operations = [
        migrations.RunSQL(
            sql=['ALTER TABLE app_tweet MODIFY text VARCHAR(255) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci'],
            reverse_sql=['ALTER TABLE app_tweet MODIFY text VARCHAR(255)']
        )
    ]
